// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main #(
 parameter v8bd423 = 5
) (
 input v67d7d5,
 input va871b0,
 output [0:3] vinit
);
 localparam p5 = v8bd423;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire w34;
 wire w35;
 wire w36;
 wire w37;
 wire w38;
 wire w39;
 wire w40;
 wire w41;
 wire w42;
 wire w43;
 wire w44;
 wire w45;
 wire w46;
 wire w47;
 wire w48;
 wire w49;
 wire w50;
 wire w51;
 wire w52;
 wire w53;
 wire w54;
 wire w55;
 wire w56;
 wire w57;
 wire w58;
 wire w59;
 wire w60;
 wire w61;
 wire w62;
 wire w63;
 wire w64;
 wire w65;
 wire w66;
 wire w67;
 wire w68;
 wire w69;
 wire w70;
 wire w71;
 wire w72;
 wire w73;
 assign w4 = v67d7d5;
 assign w40 = va871b0;
 assign w37 = w36;
 assign w38 = w36;
 assign w38 = w37;
 assign w39 = w36;
 assign w39 = w37;
 assign w39 = w38;
 assign w43 = w42;
 assign w44 = w42;
 assign w44 = w43;
 assign w45 = w42;
 assign w45 = w43;
 assign w45 = w44;
 assign w46 = w42;
 assign w46 = w43;
 assign w46 = w44;
 assign w46 = w45;
 assign w47 = w42;
 assign w47 = w43;
 assign w47 = w44;
 assign w47 = w45;
 assign w47 = w46;
 assign w48 = w42;
 assign w48 = w43;
 assign w48 = w44;
 assign w48 = w45;
 assign w48 = w46;
 assign w48 = w47;
 assign w49 = w42;
 assign w49 = w43;
 assign w49 = w44;
 assign w49 = w45;
 assign w49 = w46;
 assign w49 = w47;
 assign w49 = w48;
 assign w50 = w42;
 assign w50 = w43;
 assign w50 = w44;
 assign w50 = w45;
 assign w50 = w46;
 assign w50 = w47;
 assign w50 = w48;
 assign w50 = w49;
 assign w51 = w42;
 assign w51 = w43;
 assign w51 = w44;
 assign w51 = w45;
 assign w51 = w46;
 assign w51 = w47;
 assign w51 = w48;
 assign w51 = w49;
 assign w51 = w50;
 assign w52 = w42;
 assign w52 = w43;
 assign w52 = w44;
 assign w52 = w45;
 assign w52 = w46;
 assign w52 = w47;
 assign w52 = w48;
 assign w52 = w49;
 assign w52 = w50;
 assign w52 = w51;
 assign w53 = w42;
 assign w53 = w43;
 assign w53 = w44;
 assign w53 = w45;
 assign w53 = w46;
 assign w53 = w47;
 assign w53 = w48;
 assign w53 = w49;
 assign w53 = w50;
 assign w53 = w51;
 assign w53 = w52;
 assign w54 = w42;
 assign w54 = w43;
 assign w54 = w44;
 assign w54 = w45;
 assign w54 = w46;
 assign w54 = w47;
 assign w54 = w48;
 assign w54 = w49;
 assign w54 = w50;
 assign w54 = w51;
 assign w54 = w52;
 assign w54 = w53;
 assign w55 = w42;
 assign w55 = w43;
 assign w55 = w44;
 assign w55 = w45;
 assign w55 = w46;
 assign w55 = w47;
 assign w55 = w48;
 assign w55 = w49;
 assign w55 = w50;
 assign w55 = w51;
 assign w55 = w52;
 assign w55 = w53;
 assign w55 = w54;
 assign w56 = w42;
 assign w56 = w43;
 assign w56 = w44;
 assign w56 = w45;
 assign w56 = w46;
 assign w56 = w47;
 assign w56 = w48;
 assign w56 = w49;
 assign w56 = w50;
 assign w56 = w51;
 assign w56 = w52;
 assign w56 = w53;
 assign w56 = w54;
 assign w56 = w55;
 assign w57 = w42;
 assign w57 = w43;
 assign w57 = w44;
 assign w57 = w45;
 assign w57 = w46;
 assign w57 = w47;
 assign w57 = w48;
 assign w57 = w49;
 assign w57 = w50;
 assign w57 = w51;
 assign w57 = w52;
 assign w57 = w53;
 assign w57 = w54;
 assign w57 = w55;
 assign w57 = w56;
 assign w58 = w42;
 assign w58 = w43;
 assign w58 = w44;
 assign w58 = w45;
 assign w58 = w46;
 assign w58 = w47;
 assign w58 = w48;
 assign w58 = w49;
 assign w58 = w50;
 assign w58 = w51;
 assign w58 = w52;
 assign w58 = w53;
 assign w58 = w54;
 assign w58 = w55;
 assign w58 = w56;
 assign w58 = w57;
 assign w59 = w42;
 assign w59 = w43;
 assign w59 = w44;
 assign w59 = w45;
 assign w59 = w46;
 assign w59 = w47;
 assign w59 = w48;
 assign w59 = w49;
 assign w59 = w50;
 assign w59 = w51;
 assign w59 = w52;
 assign w59 = w53;
 assign w59 = w54;
 assign w59 = w55;
 assign w59 = w56;
 assign w59 = w57;
 assign w59 = w58;
 assign w60 = w42;
 assign w60 = w43;
 assign w60 = w44;
 assign w60 = w45;
 assign w60 = w46;
 assign w60 = w47;
 assign w60 = w48;
 assign w60 = w49;
 assign w60 = w50;
 assign w60 = w51;
 assign w60 = w52;
 assign w60 = w53;
 assign w60 = w54;
 assign w60 = w55;
 assign w60 = w56;
 assign w60 = w57;
 assign w60 = w58;
 assign w60 = w59;
 assign w61 = w42;
 assign w61 = w43;
 assign w61 = w44;
 assign w61 = w45;
 assign w61 = w46;
 assign w61 = w47;
 assign w61 = w48;
 assign w61 = w49;
 assign w61 = w50;
 assign w61 = w51;
 assign w61 = w52;
 assign w61 = w53;
 assign w61 = w54;
 assign w61 = w55;
 assign w61 = w56;
 assign w61 = w57;
 assign w61 = w58;
 assign w61 = w59;
 assign w61 = w60;
 assign w62 = w42;
 assign w62 = w43;
 assign w62 = w44;
 assign w62 = w45;
 assign w62 = w46;
 assign w62 = w47;
 assign w62 = w48;
 assign w62 = w49;
 assign w62 = w50;
 assign w62 = w51;
 assign w62 = w52;
 assign w62 = w53;
 assign w62 = w54;
 assign w62 = w55;
 assign w62 = w56;
 assign w62 = w57;
 assign w62 = w58;
 assign w62 = w59;
 assign w62 = w60;
 assign w62 = w61;
 assign w63 = w42;
 assign w63 = w43;
 assign w63 = w44;
 assign w63 = w45;
 assign w63 = w46;
 assign w63 = w47;
 assign w63 = w48;
 assign w63 = w49;
 assign w63 = w50;
 assign w63 = w51;
 assign w63 = w52;
 assign w63 = w53;
 assign w63 = w54;
 assign w63 = w55;
 assign w63 = w56;
 assign w63 = w57;
 assign w63 = w58;
 assign w63 = w59;
 assign w63 = w60;
 assign w63 = w61;
 assign w63 = w62;
 assign w64 = w42;
 assign w64 = w43;
 assign w64 = w44;
 assign w64 = w45;
 assign w64 = w46;
 assign w64 = w47;
 assign w64 = w48;
 assign w64 = w49;
 assign w64 = w50;
 assign w64 = w51;
 assign w64 = w52;
 assign w64 = w53;
 assign w64 = w54;
 assign w64 = w55;
 assign w64 = w56;
 assign w64 = w57;
 assign w64 = w58;
 assign w64 = w59;
 assign w64 = w60;
 assign w64 = w61;
 assign w64 = w62;
 assign w64 = w63;
 assign w65 = w42;
 assign w65 = w43;
 assign w65 = w44;
 assign w65 = w45;
 assign w65 = w46;
 assign w65 = w47;
 assign w65 = w48;
 assign w65 = w49;
 assign w65 = w50;
 assign w65 = w51;
 assign w65 = w52;
 assign w65 = w53;
 assign w65 = w54;
 assign w65 = w55;
 assign w65 = w56;
 assign w65 = w57;
 assign w65 = w58;
 assign w65 = w59;
 assign w65 = w60;
 assign w65 = w61;
 assign w65 = w62;
 assign w65 = w63;
 assign w65 = w64;
 assign w66 = w42;
 assign w66 = w43;
 assign w66 = w44;
 assign w66 = w45;
 assign w66 = w46;
 assign w66 = w47;
 assign w66 = w48;
 assign w66 = w49;
 assign w66 = w50;
 assign w66 = w51;
 assign w66 = w52;
 assign w66 = w53;
 assign w66 = w54;
 assign w66 = w55;
 assign w66 = w56;
 assign w66 = w57;
 assign w66 = w58;
 assign w66 = w59;
 assign w66 = w60;
 assign w66 = w61;
 assign w66 = w62;
 assign w66 = w63;
 assign w66 = w64;
 assign w66 = w65;
 assign w67 = w42;
 assign w67 = w43;
 assign w67 = w44;
 assign w67 = w45;
 assign w67 = w46;
 assign w67 = w47;
 assign w67 = w48;
 assign w67 = w49;
 assign w67 = w50;
 assign w67 = w51;
 assign w67 = w52;
 assign w67 = w53;
 assign w67 = w54;
 assign w67 = w55;
 assign w67 = w56;
 assign w67 = w57;
 assign w67 = w58;
 assign w67 = w59;
 assign w67 = w60;
 assign w67 = w61;
 assign w67 = w62;
 assign w67 = w63;
 assign w67 = w64;
 assign w67 = w65;
 assign w67 = w66;
 assign w68 = w42;
 assign w68 = w43;
 assign w68 = w44;
 assign w68 = w45;
 assign w68 = w46;
 assign w68 = w47;
 assign w68 = w48;
 assign w68 = w49;
 assign w68 = w50;
 assign w68 = w51;
 assign w68 = w52;
 assign w68 = w53;
 assign w68 = w54;
 assign w68 = w55;
 assign w68 = w56;
 assign w68 = w57;
 assign w68 = w58;
 assign w68 = w59;
 assign w68 = w60;
 assign w68 = w61;
 assign w68 = w62;
 assign w68 = w63;
 assign w68 = w64;
 assign w68 = w65;
 assign w68 = w66;
 assign w68 = w67;
 assign w69 = w42;
 assign w69 = w43;
 assign w69 = w44;
 assign w69 = w45;
 assign w69 = w46;
 assign w69 = w47;
 assign w69 = w48;
 assign w69 = w49;
 assign w69 = w50;
 assign w69 = w51;
 assign w69 = w52;
 assign w69 = w53;
 assign w69 = w54;
 assign w69 = w55;
 assign w69 = w56;
 assign w69 = w57;
 assign w69 = w58;
 assign w69 = w59;
 assign w69 = w60;
 assign w69 = w61;
 assign w69 = w62;
 assign w69 = w63;
 assign w69 = w64;
 assign w69 = w65;
 assign w69 = w66;
 assign w69 = w67;
 assign w69 = w68;
 assign w70 = w42;
 assign w70 = w43;
 assign w70 = w44;
 assign w70 = w45;
 assign w70 = w46;
 assign w70 = w47;
 assign w70 = w48;
 assign w70 = w49;
 assign w70 = w50;
 assign w70 = w51;
 assign w70 = w52;
 assign w70 = w53;
 assign w70 = w54;
 assign w70 = w55;
 assign w70 = w56;
 assign w70 = w57;
 assign w70 = w58;
 assign w70 = w59;
 assign w70 = w60;
 assign w70 = w61;
 assign w70 = w62;
 assign w70 = w63;
 assign w70 = w64;
 assign w70 = w65;
 assign w70 = w66;
 assign w70 = w67;
 assign w70 = w68;
 assign w70 = w69;
 assign w71 = w42;
 assign w71 = w43;
 assign w71 = w44;
 assign w71 = w45;
 assign w71 = w46;
 assign w71 = w47;
 assign w71 = w48;
 assign w71 = w49;
 assign w71 = w50;
 assign w71 = w51;
 assign w71 = w52;
 assign w71 = w53;
 assign w71 = w54;
 assign w71 = w55;
 assign w71 = w56;
 assign w71 = w57;
 assign w71 = w58;
 assign w71 = w59;
 assign w71 = w60;
 assign w71 = w61;
 assign w71 = w62;
 assign w71 = w63;
 assign w71 = w64;
 assign w71 = w65;
 assign w71 = w66;
 assign w71 = w67;
 assign w71 = w68;
 assign w71 = w69;
 assign w71 = w70;
 assign w72 = w42;
 assign w72 = w43;
 assign w72 = w44;
 assign w72 = w45;
 assign w72 = w46;
 assign w72 = w47;
 assign w72 = w48;
 assign w72 = w49;
 assign w72 = w50;
 assign w72 = w51;
 assign w72 = w52;
 assign w72 = w53;
 assign w72 = w54;
 assign w72 = w55;
 assign w72 = w56;
 assign w72 = w57;
 assign w72 = w58;
 assign w72 = w59;
 assign w72 = w60;
 assign w72 = w61;
 assign w72 = w62;
 assign w72 = w63;
 assign w72 = w64;
 assign w72 = w65;
 assign w72 = w66;
 assign w72 = w67;
 assign w72 = w68;
 assign w72 = w69;
 assign w72 = w70;
 assign w72 = w71;
 assign w73 = w42;
 assign w73 = w43;
 assign w73 = w44;
 assign w73 = w45;
 assign w73 = w46;
 assign w73 = w47;
 assign w73 = w48;
 assign w73 = w49;
 assign w73 = w50;
 assign w73 = w51;
 assign w73 = w52;
 assign w73 = w53;
 assign w73 = w54;
 assign w73 = w55;
 assign w73 = w56;
 assign w73 = w57;
 assign w73 = w58;
 assign w73 = w59;
 assign w73 = w60;
 assign w73 = w61;
 assign w73 = w62;
 assign w73 = w63;
 assign w73 = w64;
 assign w73 = w65;
 assign w73 = w66;
 assign w73 = w67;
 assign w73 = w68;
 assign w73 = w69;
 assign w73 = w70;
 assign w73 = w71;
 assign w73 = w72;
 v5acce8 v23bc84 (
  .v9ed4fe(w0),
  .v55dfde(w41),
  .vfea254(w42)
 );
 v5acce8 v5af3fc (
  .v55dfde(w0),
  .v9ed4fe(w30),
  .vfea254(w43)
 );
 v5acce8 vb9758d (
  .v9ed4fe(w1),
  .v55dfde(w31),
  .vfea254(w44)
 );
 v5acce8 v1d27af (
  .v55dfde(w1),
  .v9ed4fe(w2),
  .vfea254(w45)
 );
 v5acce8 v2810d7 (
  .v55dfde(w2),
  .v9ed4fe(w3),
  .vfea254(w46)
 );
 v5acce8 v68bfc6 (
  .v55dfde(w3),
  .v9ed4fe(w32),
  .vfea254(w47)
 );
 v5acce8 vacaa7c (
  .v55dfde(w33),
  .v9ed4fe(w34),
  .vfea254(w48)
 );
 v5acce8 v4de349 (
  .v9ed4fe(w13),
  .v55dfde(w35),
  .vfea254(w49)
 );
 v6a5074 #(
  .v100e1b(p5)
 ) v29af5d (
  .v0daa9e(w4),
  .v2efea4(w42)
 );
 v5acce8 v7af420 (
  .v9ed4fe(w6),
  .v55dfde(w13),
  .vfea254(w50)
 );
 v5acce8 v39a5d2 (
  .v55dfde(w6),
  .v9ed4fe(w7),
  .vfea254(w51)
 );
 v5acce8 vbba409 (
  .v55dfde(w7),
  .v9ed4fe(w8),
  .vfea254(w52)
 );
 v5acce8 v60252c (
  .v55dfde(w8),
  .v9ed4fe(w9),
  .vfea254(w53)
 );
 v5acce8 v2c8552 (
  .v55dfde(w9),
  .v9ed4fe(w10),
  .vfea254(w54)
 );
 v5acce8 vcd3261 (
  .v55dfde(w10),
  .v9ed4fe(w11),
  .vfea254(w55)
 );
 v5acce8 vc8b97c (
  .v55dfde(w11),
  .v9ed4fe(w12),
  .vfea254(w56)
 );
 v5acce8 v8a12ab (
  .v55dfde(w12),
  .v9ed4fe(w29),
  .vfea254(w57)
 );
 v5acce8 v561d22 (
  .v9ed4fe(w14),
  .v55dfde(w29),
  .vfea254(w58)
 );
 v5acce8 v448154 (
  .v55dfde(w14),
  .v9ed4fe(w15),
  .vfea254(w59)
 );
 v5acce8 vf61f9e (
  .v55dfde(w15),
  .v9ed4fe(w16),
  .vfea254(w60)
 );
 v5acce8 vf991fe (
  .v55dfde(w16),
  .v9ed4fe(w17),
  .vfea254(w61)
 );
 v5acce8 v75cf5e (
  .v55dfde(w17),
  .v9ed4fe(w18),
  .vfea254(w62)
 );
 v5acce8 vc65c3f (
  .v55dfde(w18),
  .v9ed4fe(w19),
  .vfea254(w63)
 );
 v5acce8 vf22907 (
  .v55dfde(w19),
  .v9ed4fe(w20),
  .vfea254(w64)
 );
 v5acce8 v035899 (
  .v55dfde(w20),
  .v9ed4fe(w21),
  .vfea254(w65)
 );
 v5acce8 v57977b (
  .v55dfde(w21),
  .v9ed4fe(w22),
  .vfea254(w66)
 );
 v5acce8 v3a6c23 (
  .v55dfde(w22),
  .v9ed4fe(w23),
  .vfea254(w67)
 );
 v5acce8 v8087f0 (
  .v55dfde(w23),
  .v9ed4fe(w24),
  .vfea254(w68)
 );
 v5acce8 va0d570 (
  .v55dfde(w24),
  .v9ed4fe(w25),
  .vfea254(w69)
 );
 v5acce8 v95377b (
  .v55dfde(w25),
  .v9ed4fe(w26),
  .vfea254(w70)
 );
 v5acce8 v2568f1 (
  .v55dfde(w26),
  .v9ed4fe(w27),
  .vfea254(w71)
 );
 v5acce8 vb745cf (
  .v55dfde(w27),
  .v9ed4fe(w28),
  .vfea254(w72)
 );
 v5acce8 vdbb96d (
  .v55dfde(w28),
  .v9ed4fe(w36),
  .vfea254(w73)
 );
 v18c17a v2cc132 (
  .v3ca442(w30),
  .vcbab45(w31),
  .v0e28cb(w38)
 );
 v18c17a ve7d250 (
  .v3ca442(w32),
  .vcbab45(w33),
  .v0e28cb(w37)
 );
 v18c17a v6fe92c (
  .v3ca442(w34),
  .vcbab45(w35),
  .v0e28cb(w36)
 );
 v873425 v21909c (
  .v0e28cb(w39),
  .v3ca442(w40),
  .vcbab45(w41)
 );
 assign vinit = 4'b0000;
endmodule

//---- Top entity
module v5acce8 (
 input v55dfde,
 input vfea254,
 output v9ed4fe
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = vfea254;
 assign w1 = v55dfde;
 assign v9ed4fe = w2;
 v58ed2b v06c055 (
  .va4102a(w0),
  .vf54559(w1),
  .ve8318d(w2)
 );
endmodule

//---------------------------------------------------
//-- MemCell
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module v58ed2b #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output va58c5b,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v58ed2b_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- sys-DFF-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- System - D Flip-flop. Capture data every system clock cycle. Verilog implementation
//---------------------------------------------------

module v58ed2b_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg qi = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   qi <= d;
   
 //-- Connect the register with the
 //-- output
 assign q = qi;
endmodule
//---- Top entity
module v6a5074 #(
 parameter v100e1b = 22
) (
 input v0daa9e,
 output v2efea4
);
 localparam p2 = v100e1b;
 wire w0;
 wire w1;
 assign v2efea4 = w0;
 assign w1 = v0daa9e;
 v6a5074_vac7386 #(
  .N(p2)
 ) vac7386 (
  .clk_out(w0),
  .clk_in(w1)
 );
endmodule

//---------------------------------------------------
//-- PrescalerN
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Parametric N-bits prescaler
//---------------------------------------------------

module v6a5074_vac7386 #(
 parameter N = 0
) (
 input clk_in,
 output clk_out
);
 //-- Number of bits of the prescaler
 //parameter N = 22;
 
 //-- divisor register
 reg [N-1:0] divcounter;
 
 //-- N bit counter
 always @(posedge clk_in)
   divcounter <= divcounter + 1;
 
 //-- Use the most significant bit as output
 assign clk_out = divcounter[N-1];
endmodule
//---- Top entity
module v18c17a (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v18c17a_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR2-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR gate: 2-bits input xor gate. Verilog implementation
//---------------------------------------------------

module v18c17a_vf4938a (
 input a,
 input b,
 output c
);
 //-- XOR gate
 //-- Verilog implementation
 
 assign c = a ^ b;
 
endmodule
//---- Top entity
module v873425 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v873425_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- OR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR2: Two bits input OR gate
//---------------------------------------------------

module v873425_vf4938a (
 input a,
 input b,
 output c
);
 //-- OR Gate
 //-- Verilog implementation
 
 assign c = a | b;
 
 
endmodule
