// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input v8b6dc2,
 input v7688b1,
 input v03f33c,
 input v01fe61,
 input vbe8090,
 output v1d13ab,
 output vb005a0,
 output v6f156b,
 output vc25e86,
 output v040e7a,
 output vfd8812,
 output vd6d5c1,
 output v20e72f,
 output v7a2bc1,
 output v1bdc7b,
 output v460376,
 output v4b2f9c
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire [0:2] w21;
 wire [0:2] w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire w34;
 wire w35;
 wire w36;
 wire w37;
 wire w38;
 wire w39;
 wire w40;
 wire w41;
 wire w42;
 wire w43;
 wire w44;
 wire w45;
 wire w46;
 wire w47;
 wire w48;
 wire w49;
 wire w50;
 wire w51;
 wire w52;
 wire w53;
 wire w54;
 wire w55;
 wire w56;
 wire w57;
 wire w58;
 wire w59;
 wire w60;
 wire w61;
 wire w62;
 wire w63;
 wire w64;
 wire w65;
 wire w66;
 wire w67;
 wire w68;
 wire w69;
 wire w70;
 wire w71;
 wire w72;
 wire w73;
 wire w74;
 wire w75;
 wire w76;
 wire w77;
 wire w78;
 wire w79;
 wire w80;
 wire w81;
 wire w82;
 wire w83;
 wire w84;
 wire w85;
 wire w86;
 wire w87;
 wire w88;
 wire w89;
 wire w90;
 wire w91;
 wire w92;
 wire w93;
 wire w94;
 wire w95;
 wire w96;
 wire w97;
 wire w98;
 wire w99;
 wire w100;
 wire w101;
 wire w102;
 wire w103;
 wire w104;
 wire w105;
 wire w106;
 wire w107;
 wire w108;
 wire w109;
 wire w110;
 wire w111;
 wire w112;
 wire w113;
 wire w114;
 wire w115;
 wire w116;
 wire w117;
 wire w118;
 wire w119;
 wire w120;
 assign w6 = vbe8090;
 assign w7 = v01fe61;
 assign w8 = v03f33c;
 assign w9 = v7688b1;
 assign vb005a0 = w36;
 assign vd6d5c1 = w37;
 assign v040e7a = w42;
 assign w45 = v8b6dc2;
 assign w46 = v8b6dc2;
 assign v1d13ab = w46;
 assign w47 = v8b6dc2;
 assign v460376 = w53;
 assign v4b2f9c = w69;
 assign vc25e86 = w90;
 assign v6f156b = w97;
 assign vfd8812 = w106;
 assign v20e72f = w109;
 assign v7a2bc1 = w112;
 assign v1bdc7b = w117;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w14 = w13;
 assign w40 = w39;
 assign w41 = w39;
 assign w41 = w40;
 assign w42 = w39;
 assign w42 = w40;
 assign w42 = w41;
 assign w43 = w39;
 assign w43 = w40;
 assign w43 = w41;
 assign w43 = w42;
 assign w44 = w39;
 assign w44 = w40;
 assign w44 = w41;
 assign w44 = w42;
 assign w44 = w43;
 assign w46 = w45;
 assign w47 = w45;
 assign w47 = w46;
 assign w50 = w49;
 assign w51 = w49;
 assign w51 = w50;
 assign w52 = w49;
 assign w52 = w50;
 assign w52 = w51;
 assign w53 = w49;
 assign w53 = w50;
 assign w53 = w51;
 assign w53 = w52;
 assign w54 = w49;
 assign w54 = w50;
 assign w54 = w51;
 assign w54 = w52;
 assign w54 = w53;
 assign w55 = w49;
 assign w55 = w50;
 assign w55 = w51;
 assign w55 = w52;
 assign w55 = w53;
 assign w55 = w54;
 assign w57 = w56;
 assign w59 = w58;
 assign w60 = w58;
 assign w60 = w59;
 assign w61 = w58;
 assign w61 = w59;
 assign w61 = w60;
 assign w62 = w58;
 assign w62 = w59;
 assign w62 = w60;
 assign w62 = w61;
 assign w63 = w58;
 assign w63 = w59;
 assign w63 = w60;
 assign w63 = w61;
 assign w63 = w62;
 assign w64 = w58;
 assign w64 = w59;
 assign w64 = w60;
 assign w64 = w61;
 assign w64 = w62;
 assign w64 = w63;
 assign w66 = w65;
 assign w67 = w65;
 assign w67 = w66;
 assign w68 = w65;
 assign w68 = w66;
 assign w68 = w67;
 assign w69 = w65;
 assign w69 = w66;
 assign w69 = w67;
 assign w69 = w68;
 assign w70 = w65;
 assign w70 = w66;
 assign w70 = w67;
 assign w70 = w68;
 assign w70 = w69;
 assign w71 = w65;
 assign w71 = w66;
 assign w71 = w67;
 assign w71 = w68;
 assign w71 = w69;
 assign w71 = w70;
 assign w74 = w73;
 assign w75 = w73;
 assign w75 = w74;
 assign w76 = w73;
 assign w76 = w74;
 assign w76 = w75;
 assign w77 = w73;
 assign w77 = w74;
 assign w77 = w75;
 assign w77 = w76;
 assign w78 = w73;
 assign w78 = w74;
 assign w78 = w75;
 assign w78 = w76;
 assign w78 = w77;
 assign w79 = w73;
 assign w79 = w74;
 assign w79 = w75;
 assign w79 = w76;
 assign w79 = w77;
 assign w79 = w78;
 assign w81 = w80;
 assign w82 = w80;
 assign w82 = w81;
 assign w83 = w80;
 assign w83 = w81;
 assign w83 = w82;
 assign w84 = w80;
 assign w84 = w81;
 assign w84 = w82;
 assign w84 = w83;
 assign w85 = w80;
 assign w85 = w81;
 assign w85 = w82;
 assign w85 = w83;
 assign w85 = w84;
 assign w86 = w80;
 assign w86 = w81;
 assign w86 = w82;
 assign w86 = w83;
 assign w86 = w84;
 assign w86 = w85;
 assign w88 = w87;
 assign w89 = w87;
 assign w89 = w88;
 assign w90 = w87;
 assign w90 = w88;
 assign w90 = w89;
 assign w91 = w87;
 assign w91 = w88;
 assign w91 = w89;
 assign w91 = w90;
 assign w92 = w87;
 assign w92 = w88;
 assign w92 = w89;
 assign w92 = w90;
 assign w92 = w91;
 assign w94 = w93;
 assign w97 = w96;
 assign w98 = w96;
 assign w98 = w97;
 assign w101 = w100;
 assign w105 = w104;
 assign w107 = w106;
 assign w108 = w106;
 assign w108 = w107;
 assign w110 = w109;
 assign w111 = w109;
 assign w111 = w110;
 assign w113 = w112;
 assign w114 = w112;
 assign w114 = w113;
 assign w116 = w115;
 assign w118 = w117;
 assign w119 = w117;
 assign w119 = w118;
 vc17c7e va159a4 (
  .ve86251(w39),
  .v0e28cb(w49),
  .vcbab45(w56),
  .v3ca442(w65)
 );
 vd46be5 v7db1f5 (
  .v3ca442(w0),
  .v1b1eae(w1),
  .v141a59(w2),
  .v0e28cb(w87),
  .vcbab45(w93)
 );
 v3676a0 v26617c (
  .vcbab45(w2),
  .v0e28cb(w66)
 );
 v3676a0 v89aaa4 (
  .vcbab45(w1),
  .v0e28cb(w50)
 );
 v3676a0 va1519c (
  .vcbab45(w0),
  .v0e28cb(w40)
 );
 vc17c7e vde87a0 (
  .v0e28cb(w51),
  .v3ca442(w67),
  .ve86251(w88),
  .vcbab45(w100)
 );
 v3676a0 ve4ba8c (
  .vcbab45(w5),
  .v0e28cb(w70)
 );
 v3676a0 v483e69 (
  .vcbab45(w4),
  .v0e28cb(w54)
 );
 v3676a0 v08e46d (
  .vcbab45(w3),
  .v0e28cb(w91)
 );
 vd46be5 vcb8704 (
  .v0e28cb(w3),
  .v1b1eae(w4),
  .v141a59(w5),
  .v3ca442(w43),
  .vcbab45(w115)
 );
 v073659 vcdbc6f (
  .v0e28cb(w44),
  .v3ca442(w55),
  .vb1969b(w71),
  .ve86251(w92),
  .vcbab45(w120)
 );
 v016822 v3ee644 (
  .va65bee(w10),
  .vb07d28(w11),
  .vcb28b3(w12),
  .vc117f6(w38),
  .v88c2ed(w48),
  .va00921(w59),
  .v1b565e(w72),
  .va83de4(w74),
  .v5331ef(w81),
  .vd326c3(w95),
  .va48b72(w99),
  .vf24815(w102),
  .v55292b(w103),
  .v71f37c(w104)
 );
 v74c286 v48c021 (
  .v26e436(w13),
  .vb772be(w14),
  .v635938(w15),
  .v921d60(w38),
  .v53e727(w48),
  .va4ae88(w58),
  .v49c067(w72),
  .v25b854(w73),
  .v464cc6(w80)
 );
 vb1c867 v125ba1 (
  .v3e83a1(w47),
  .vaa2332(w58),
  .v1c95bf(w73),
  .v289238(w80),
  .vead872(w95),
  .ve86d71(w99),
  .vc38257(w102)
 );
 vd30ca9 vad17c9 (
  .v9fb85f(w10)
 );
 vfebcfe v2f2e22 (
  .v9fb85f(w15)
 );
 vd30ca9 v405fff (
  .v9fb85f(w13)
 );
 vba518e v538e70 (
  .vcbab45(w18),
  .v3ca442(w93),
  .v0e28cb(w118)
 );
 vba518e v51b7fa (
  .vcbab45(w19),
  .v0e28cb(w107),
  .v3ca442(w115)
 );
 vba518e v8dbc15 (
  .vcbab45(w20),
  .v0e28cb(w110),
  .v3ca442(w116)
 );
 vba518e vb3dc86 (
  .v3ca442(w16),
  .v0e28cb(w17),
  .vcbab45(w103)
 );
 v3676a0 v893f87 (
  .vcbab45(w17),
  .v0e28cb(w105)
 );
 vef0330 vdbd235 (
  .v5568ce(w21),
  .v6af287(w22)
 );
 v2b9b8c vafc3c3 (
  .ve52f8a(w21),
  .vf8041d(w60),
  .vee8a83(w75),
  .v03aaf0(w82)
 );
 v862e66 ve536c8 (
  .v28a8d2(w22),
  .vcbab45(w117)
 );
 v9a0147 v65f04e (
  .v1b1eae(w23),
  .v3ca442(w24),
  .v0e28cb(w61),
  .vcbab45(w106)
 );
 v3676a0 v5b0280 (
  .vcbab45(w24),
  .v0e28cb(w76)
 );
 v3676a0 vea9644 (
  .vcbab45(w23),
  .v0e28cb(w83)
 );
 v9a0147 v4d0254 (
  .v0e28cb(w26),
  .v1b1eae(w27),
  .v3ca442(w77),
  .vcbab45(w109)
 );
 v3676a0 vd21c95 (
  .vcbab45(w26),
  .v0e28cb(w62)
 );
 v3676a0 vb0d8ba (
  .vcbab45(w27),
  .v0e28cb(w84)
 );
 v9a0147 v017f5e (
  .v1b1eae(w25),
  .v0e28cb(w63),
  .v3ca442(w78),
  .vcbab45(w112)
 );
 v3676a0 v8cd29b (
  .vcbab45(w25),
  .v0e28cb(w85)
 );
 v9a0147 v4f25f1 (
  .v0e28cb(w28),
  .v3ca442(w29),
  .v1b1eae(w86),
  .vcbab45(w96)
 );
 v3676a0 vb20cbb (
  .vcbab45(w29),
  .v0e28cb(w79)
 );
 v3676a0 v04af3e (
  .vcbab45(w28),
  .v0e28cb(w64)
 );
 v073659 v3baeea (
  .vcbab45(w16),
  .ve86251(w18),
  .v0e28cb(w19),
  .v3ca442(w20),
  .vb1969b(w30)
 );
 vba518e ve78c22 (
  .vcbab45(w30),
  .v3ca442(w94),
  .v0e28cb(w113)
 );
 v50a2d1 vfd2809 (
  .v324d03(w31),
  .vb1969b(w32),
  .v3ca442(w33),
  .v0e28cb(w34),
  .ve86251(w35),
  .vcbab45(w104)
 );
 vba518e v18db45 (
  .vcbab45(w35),
  .v3ca442(w56),
  .v0e28cb(w119)
 );
 vba518e v98c7b2 (
  .vcbab45(w34),
  .v3ca442(w100),
  .v0e28cb(w108)
 );
 vba518e va341ee (
  .vcbab45(w33),
  .v3ca442(w101),
  .v0e28cb(w111)
 );
 vba518e va56cb6 (
  .vcbab45(w32),
  .v3ca442(w57),
  .v0e28cb(w114)
 );
 vba518e vd46caf (
  .vcbab45(w31),
  .v0e28cb(w98),
  .v3ca442(w120)
 );
 v3676a0 v1e8b34 (
  .vcbab45(w36),
  .v0e28cb(w96)
 );
 v9e24f2 vedff97 (
  .vcaf019(w6),
  .v31dfe6(w7),
  .vc5c5cb(w8),
  .vd1cefe(w9),
  .v21b970(w39),
  .v344eeb(w45),
  .v1c6536(w49),
  .vccbb9b(w65),
  .v179a5c(w87)
 );
 v073659 vcc34d2 (
  .vcbab45(w37),
  .v0e28cb(w41),
  .v3ca442(w52),
  .vb1969b(w68),
  .ve86251(w89)
 );
endmodule

//---- Top entity
module vc17c7e (
 input ve86251,
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign vcbab45 = w0;
 assign w1 = ve86251;
 assign w2 = v0e28cb;
 assign w3 = v3ca442;
 vc17c7e_v99a034 v99a034 (
  .o(w0),
  .a(w1),
  .b(w2),
  .c(w3)
 );
endmodule

//---------------------------------------------------
//-- OR3-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR3-verilog: 3-bits input OR gate. Verilog implementation
//---------------------------------------------------

module vc17c7e_v99a034 (
 input a,
 input b,
 input c,
 output o
);
 assign o = a | b | c;
endmodule
//---- Top entity
module vd46be5 (
 input v0e28cb,
 input v3ca442,
 input v1b1eae,
 input v141a59,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign w2 = v1b1eae;
 assign vcbab45 = w3;
 assign w4 = v141a59;
 vd46be5_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2),
  .o(w3),
  .d(w4)
 );
endmodule

//---------------------------------------------------
//-- AND4-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AND4-verilog. 4-bits input And gate. Verilog implementation
//---------------------------------------------------

module vd46be5_vf4938a (
 input a,
 input b,
 input c,
 input d,
 output o
);
 //-- AND gate
 //-- Verilog implementation
 
 assign o = a & b & c & d;
 
endmodule
//---- Top entity
module v3676a0 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v3676a0_vd54ca1 vd54ca1 (
  .a(w0),
  .q(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- NOT gate (Verilog implementation)
//---------------------------------------------------

module v3676a0_vd54ca1 (
 input a,
 output q
);
 //-- NOT Gate
 assign q = ~a;
 
 
endmodule
//---- Top entity
module v073659 (
 input ve86251,
 input v0e28cb,
 input v3ca442,
 input vb1969b,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign vcbab45 = w0;
 assign w1 = ve86251;
 assign w2 = v0e28cb;
 assign w3 = v3ca442;
 assign w4 = vb1969b;
 v073659_v99a034 v99a034 (
  .o(w0),
  .a(w1),
  .b(w2),
  .c(w3),
  .d(w4)
 );
endmodule

//---------------------------------------------------
//-- OR4-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR4-verilog: 4-bits input OR gate. Verilog implementation
//---------------------------------------------------

module v073659_v99a034 (
 input a,
 input b,
 input c,
 input d,
 output o
);
 assign o = a | b | c | d;
endmodule
//---- Top entity
module v016822 (
 input va00921,
 input va83de4,
 input v5331ef,
 input vc117f6,
 input v88c2ed,
 input v1b565e,
 input va65bee,
 input vb07d28,
 input vcb28b3,
 input v55292b,
 input v71f37c,
 output vd326c3,
 output va48b72,
 output vf24815
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 assign w0 = va00921;
 assign w1 = va83de4;
 assign w2 = v5331ef;
 assign w3 = vc117f6;
 assign w4 = v88c2ed;
 assign w5 = v1b565e;
 assign w6 = vb07d28;
 assign w7 = vcb28b3;
 assign w8 = va65bee;
 assign w9 = v71f37c;
 assign w10 = v71f37c;
 assign w11 = v71f37c;
 assign w12 = v55292b;
 assign w13 = v55292b;
 assign w14 = v55292b;
 assign vd326c3 = w15;
 assign va48b72 = w16;
 assign vf24815 = w17;
 assign w10 = w9;
 assign w11 = w9;
 assign w11 = w10;
 assign w13 = w12;
 assign w14 = w12;
 assign w14 = w13;
 v22d161 v8768c4 (
  .vc574c7(w0),
  .vddbbcb(w3),
  .ve79f44(w8),
  .v5d7f47(w11),
  .v9ef2ab(w14),
  .vb07df5(w15)
 );
 v22d161 vbe0dd1 (
  .vc574c7(w1),
  .vddbbcb(w4),
  .ve79f44(w6),
  .v5d7f47(w10),
  .v9ef2ab(w13),
  .vb07df5(w16)
 );
 v22d161 v73ef4d (
  .vc574c7(w2),
  .vddbbcb(w5),
  .ve79f44(w7),
  .v5d7f47(w9),
  .v9ef2ab(w12),
  .vb07df5(w17)
 );
endmodule

//---------------------------------------------------
//-- 9:3 MUX
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module v22d161 (
 input vc574c7,
 input vddbbcb,
 input ve79f44,
 input v9ef2ab,
 input v5d7f47,
 output vb07df5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w0 = vddbbcb;
 assign w1 = vc574c7;
 assign w3 = ve79f44;
 assign w4 = v9ef2ab;
 assign w5 = v5d7f47;
 assign vb07df5 = w6;
 vc1653f vf9b6b0 (
  .vd646f9(w0),
  .vfe17e9(w1),
  .v875293(w2),
  .ve50a7b(w4)
 );
 vc1653f vd2fa96 (
  .vfe17e9(w2),
  .vd646f9(w3),
  .ve50a7b(w5),
  .v875293(w6)
 );
endmodule

//---------------------------------------------------
//-- 3:1 MUX
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module vc1653f (
 input vd646f9,
 input vfe17e9,
 input ve50a7b,
 output v875293
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign v875293 = w0;
 assign w1 = ve50a7b;
 assign w2 = vfe17e9;
 assign w3 = vd646f9;
 vc1653f_v4d0636 v4d0636 (
  .o(w0),
  .sel(w1),
  .i0(w2),
  .i1(w3)
 );
endmodule

//---------------------------------------------------
//-- Mux-2-1-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 2-to-1 Multplexer (1-bit channels). Verilog implementation
//---------------------------------------------------

module vc1653f_v4d0636 (
 input i1,
 input i0,
 input sel,
 output o
);
 //-- 2-to-1 Multiplexer 
 
 assign o = sel ? i1 : i0;
endmodule
//---- Top entity
module v74c286 (
 input v66bbf1,
 input v635938,
 input vb772be,
 input v26e436,
 input va4ae88,
 input v25b854,
 input v464cc6,
 output v921d60,
 output v53e727,
 output v49c067
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign w2 = v25b854;
 assign w3 = vb772be;
 assign w4 = va4ae88;
 assign w5 = v635938;
 assign w6 = v464cc6;
 assign w7 = v26e436;
 assign v53e727 = w8;
 assign v921d60 = w9;
 assign v49c067 = w10;
 assign w11 = v66bbf1;
 va4ba07 va26080 (
  .v194f88(w1),
  .v64d63b(w4),
  .v7966e4(w5),
  .v95e619(w9),
  .v380bca(w11)
 );
 va4ba07 v6125f9 (
  .v194f88(w0),
  .v380bca(w1),
  .v64d63b(w2),
  .v7966e4(w3),
  .v95e619(w8)
 );
 va4ba07 v313682 (
  .v380bca(w0),
  .v64d63b(w6),
  .v7966e4(w7),
  .v95e619(w10)
 );
endmodule

//---------------------------------------------------
//-- 3B ADDER
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module va4ba07 (
 input v7966e4,
 input v64d63b,
 input v380bca,
 output v95e619,
 output v194f88
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign w0 = v64d63b;
 assign w1 = v7966e4;
 assign w2 = v380bca;
 assign v95e619 = w4;
 assign w6 = v380bca;
 assign w9 = v7966e4;
 assign w10 = v64d63b;
 assign v194f88 = w11;
 assign w5 = w3;
 assign w6 = w2;
 assign w9 = w1;
 assign w10 = w0;
 v18c17a v49967d (
  .v3ca442(w0),
  .v0e28cb(w1),
  .vcbab45(w3)
 );
 v18c17a v811bf6 (
  .v3ca442(w2),
  .v0e28cb(w3),
  .vcbab45(w4)
 );
 vba518e vd8077b (
  .v0e28cb(w5),
  .v3ca442(w6),
  .vcbab45(w7)
 );
 vba518e vf4cff4 (
  .vcbab45(w8),
  .v0e28cb(w9),
  .v3ca442(w10)
 );
 v873425 v2053c6 (
  .v0e28cb(w7),
  .v3ca442(w8),
  .vcbab45(w11)
 );
endmodule

//---- Top entity
module v18c17a (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v18c17a_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR2-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR gate: 2-bits input xor gate. Verilog implementation
//---------------------------------------------------

module v18c17a_vf4938a (
 input a,
 input b,
 output c
);
 //-- XOR gate
 //-- Verilog implementation
 
 assign c = a ^ b;
 
endmodule
//---- Top entity
module vba518e (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vba518e_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- AND2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Two bits input And gate
//---------------------------------------------------

module vba518e_vf4938a (
 input a,
 input b,
 output c
);
 //-- AND gate
 //-- Verilog implementation
 
 assign c = a & b;
 
endmodule
//---- Top entity
module v873425 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v873425_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- OR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR2: Two bits input OR gate
//---------------------------------------------------

module v873425_vf4938a (
 input a,
 input b,
 output c
);
 //-- OR Gate
 //-- Verilog implementation
 
 assign c = a | b;
 
 
endmodule
//---- Top entity
module vb1c867 (
 input v3e83a1,
 input vead872,
 input ve86d71,
 input vc38257,
 output vaa2332,
 output v1c95bf,
 output v289238
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign w0 = v3e83a1;
 assign w1 = v3e83a1;
 assign w2 = v3e83a1;
 assign w3 = vead872;
 assign w4 = ve86d71;
 assign w5 = vc38257;
 assign v289238 = w6;
 assign v1c95bf = w7;
 assign vaa2332 = w8;
 assign w1 = w0;
 assign w2 = w0;
 assign w2 = w1;
 v58ed2b vcdc0e9 (
  .va4102a(w0),
  .vf54559(w3),
  .ve8318d(w8)
 );
 v58ed2b v60face (
  .va4102a(w1),
  .vf54559(w4),
  .ve8318d(w7)
 );
 v58ed2b v881c39 (
  .va4102a(w2),
  .vf54559(w5),
  .ve8318d(w6)
 );
endmodule

//---------------------------------------------------
//-- 3B REG
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module v58ed2b #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output va58c5b,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v58ed2b_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- sys-DFF-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- System - D Flip-flop. Capture data every system clock cycle. Verilog implementation
//---------------------------------------------------

module v58ed2b_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg qi = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   qi <= d;
   
 //-- Connect the register with the
 //-- output
 assign q = qi;
endmodule
//---- Top entity
module vd30ca9 (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vd30ca9_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-0
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 0
//---------------------------------------------------

module vd30ca9_vb2eccd (
 output q
);
 //-- Constant bit-0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module vfebcfe (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vfebcfe_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 1
//---------------------------------------------------

module vfebcfe_vb2eccd (
 output q
);
 //-- Constant bit-1
 assign q = 1'b1;
 
 
endmodule
//---- Top entity
module vef0330 (
 input [2:0] v5568ce,
 output [2:0] v6af287
);
 wire [0:2] w0;
 wire [0:2] w1;
 assign w0 = v5568ce;
 assign v6af287 = w1;
 vef0330_v668229 v668229 (
  .i(w0),
  .o(w1)
 );
endmodule

//---------------------------------------------------
//-- not-x3-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- not-x3-verilog: 3-bits not gate. Verilog implementation
//---------------------------------------------------

module vef0330_v668229 (
 input [2:0] i,
 output [2:0] o
);
 //-- Not Gate
 assign o =  ~i;
endmodule
//---- Top entity
module v2b9b8c (
 input vf8041d,
 input vee8a83,
 input v03aaf0,
 output [2:0] ve52f8a
);
 wire w0;
 wire w1;
 wire [0:2] w2;
 wire w3;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign ve52f8a = w2;
 assign w3 = vf8041d;
 v2b9b8c_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2),
  .i2(w3)
 );
endmodule

//---------------------------------------------------
//-- Bus3-Join-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus3-Join-all: Joint three wires into a 3-bits Bus
//---------------------------------------------------

module v2b9b8c_v9a2a06 (
 input i2,
 input i1,
 input i0,
 output [2:0] o
);
 assign o = {i2, i1, i0};
 
endmodule
//---- Top entity
module v862e66 (
 input [2:0] v28a8d2,
 output vcbab45
);
 wire w0;
 wire [0:2] w1;
 assign vcbab45 = w0;
 assign w1 = v28a8d2;
 v862e66_vef708c vef708c (
  .c(w0),
  .a(w1)
 );
endmodule

//---------------------------------------------------
//-- AND-BUS3-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AND-BUS3-verilog. And gate with 3-bits bus input. Verilog implementation
//---------------------------------------------------

module v862e66_vef708c (
 input [2:0] a,
 output c
);
 //-- AND gate
 //-- Verilog implementation
 
 assign c = &a;
 
endmodule
//---- Top entity
module v9a0147 (
 input v0e28cb,
 input v3ca442,
 input v1b1eae,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign w2 = v1b1eae;
 assign vcbab45 = w3;
 v9a0147_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2),
  .o(w3)
 );
endmodule

//---------------------------------------------------
//-- AND3-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AND3-verilog. 3- bits input And gate. Verilog implementation
//---------------------------------------------------

module v9a0147_vf4938a (
 input a,
 input b,
 input c,
 output o
);
 //-- AND gate
 //-- Verilog implementation
 
 assign o = a & b & c;
 
endmodule
//---- Top entity
module v50a2d1 (
 input ve86251,
 input v0e28cb,
 input v3ca442,
 input vb1969b,
 input v324d03,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 assign vcbab45 = w0;
 assign w1 = ve86251;
 assign w2 = v0e28cb;
 assign w3 = v3ca442;
 assign w4 = vb1969b;
 assign w5 = v324d03;
 v50a2d1_v99a034 v99a034 (
  .o(w0),
  .a(w1),
  .b(w2),
  .c(w3),
  .d(w4),
  .e(w5)
 );
endmodule

//---------------------------------------------------
//-- OR5-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR5-verilog: 5-bits input OR gate. Verilog implementation
//---------------------------------------------------

module v50a2d1_v99a034 (
 input a,
 input b,
 input c,
 input d,
 input e,
 output o
);
 assign o = a | b | c | d | e;
endmodule
//---- Top entity
module v9e24f2 (
 input v344eeb,
 input vd1cefe,
 input vc5c5cb,
 input v31dfe6,
 input vcaf019,
 output v179a5c,
 output v21b970,
 output v1c6536,
 output vccbb9b
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 assign v179a5c = w0;
 assign v21b970 = w5;
 assign v1c6536 = w10;
 assign vccbb9b = w19;
 assign w20 = vd1cefe;
 assign w21 = vcaf019;
 assign w22 = v31dfe6;
 assign w23 = vc5c5cb;
 assign w24 = v344eeb;
 assign w25 = v344eeb;
 assign w26 = v344eeb;
 assign w27 = v344eeb;
 assign w28 = v344eeb;
 assign w29 = v344eeb;
 assign w30 = v344eeb;
 assign w31 = v344eeb;
 assign w4 = w1;
 assign w9 = w6;
 assign w14 = w11;
 assign w18 = w15;
 assign w25 = w24;
 assign w26 = w24;
 assign w26 = w25;
 assign w27 = w24;
 assign w27 = w25;
 assign w27 = w26;
 assign w28 = w24;
 assign w28 = w25;
 assign w28 = w26;
 assign w28 = w27;
 assign w29 = w24;
 assign w29 = w25;
 assign w29 = w26;
 assign w29 = w27;
 assign w29 = w28;
 assign w30 = w24;
 assign w30 = w25;
 assign w30 = w26;
 assign w30 = w27;
 assign w30 = w28;
 assign w30 = w29;
 assign w31 = w24;
 assign w31 = w25;
 assign w31 = w26;
 assign w31 = w27;
 assign w31 = w28;
 assign w31 = w29;
 assign w31 = w30;
 v58ed2b vb3d304 (
  .ve8318d(w1),
  .vf54559(w20),
  .va4102a(w24)
 );
 vba518e v7435fc (
  .vcbab45(w0),
  .v3ca442(w1),
  .v0e28cb(w2)
 );
 v3676a0 vd6b7e4 (
  .vcbab45(w2),
  .v0e28cb(w3)
 );
 v58ed2b vb8f8a5 (
  .ve8318d(w3),
  .vf54559(w4),
  .va4102a(w25)
 );
 v58ed2b v4b7051 (
  .ve8318d(w6),
  .vf54559(w23),
  .va4102a(w26)
 );
 vba518e vf7df84 (
  .vcbab45(w5),
  .v3ca442(w6),
  .v0e28cb(w7)
 );
 v3676a0 v0ad11f (
  .vcbab45(w7),
  .v0e28cb(w8)
 );
 v58ed2b vc6df65 (
  .ve8318d(w8),
  .vf54559(w9),
  .va4102a(w27)
 );
 v58ed2b v4a0c3f (
  .ve8318d(w11),
  .vf54559(w22),
  .va4102a(w28)
 );
 vba518e ve3d037 (
  .vcbab45(w10),
  .v3ca442(w11),
  .v0e28cb(w12)
 );
 v3676a0 v62dc33 (
  .vcbab45(w12),
  .v0e28cb(w13)
 );
 v58ed2b vcd2777 (
  .ve8318d(w13),
  .vf54559(w14),
  .va4102a(w29)
 );
 v58ed2b vd8294c (
  .ve8318d(w15),
  .vf54559(w21),
  .va4102a(w30)
 );
 vba518e vc2e6db (
  .v3ca442(w15),
  .v0e28cb(w16),
  .vcbab45(w19)
 );
 v3676a0 v247866 (
  .vcbab45(w16),
  .v0e28cb(w17)
 );
 v58ed2b v8771e5 (
  .ve8318d(w17),
  .vf54559(w18),
  .va4102a(w31)
 );
endmodule

