// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main #(
 parameter v6d34b3 = 24
) (
 input v74aa38,
 input v57ad06,
 output vf3a86e,
 output vb1d534,
 output vd241a0,
 output vcd42c3
);
 localparam p1 = v6d34b3;
 wire w0;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 assign w0 = v74aa38;
 assign w3 = v57ad06;
 assign vcd42c3 = w4;
 assign vf3a86e = w5;
 assign vb1d534 = w6;
 assign vd241a0 = w7;
 v47ccf1 vab2cba (
  .v5e70cb(w2),
  .v2ab6c3(w3),
  .vc6cd33(w4),
  .v348605(w5),
  .v2c7c38(w6),
  .v1b915e(w7)
 );
 v6a5074 #(
  .v100e1b(p1)
 ) v84e030 (
  .v0daa9e(w0),
  .v2efea4(w2)
 );
endmodule

//---- Top entity
module v47ccf1 (
 input v5e70cb,
 input v2ab6c3,
 output v348605,
 output v2c7c38,
 output v1b915e,
 output vc6cd33
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign w0 = v5e70cb;
 assign w1 = v5e70cb;
 assign w2 = v5e70cb;
 assign w3 = v5e70cb;
 assign w7 = v2ab6c3;
 assign v348605 = w8;
 assign v2c7c38 = w9;
 assign v1b915e = w10;
 assign vc6cd33 = w11;
 assign w1 = w0;
 assign w2 = w0;
 assign w2 = w1;
 assign w3 = w0;
 assign w3 = w1;
 assign w3 = w2;
 assign w8 = w4;
 assign w9 = w5;
 assign w10 = w6;
 v58ed2b vf5e098 (
  .va4102a(w0),
  .ve8318d(w4),
  .vf54559(w7)
 );
 v58ed2b v70d5d3 (
  .va4102a(w1),
  .vf54559(w4),
  .ve8318d(w5)
 );
 v58ed2b v6ae3b0 (
  .va4102a(w2),
  .vf54559(w5),
  .ve8318d(w6)
 );
 v58ed2b v676d5d (
  .va4102a(w3),
  .vf54559(w6),
  .ve8318d(w11)
 );
endmodule

//---- Top entity
module v58ed2b #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output va58c5b,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v58ed2b_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- sys-DFF-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- System - D Flip-flop. Capture data every system clock cycle. Verilog implementation
//---------------------------------------------------

module v58ed2b_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg qi = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   qi <= d;
   
 //-- Connect the register with the
 //-- output
 assign q = qi;
endmodule
//---- Top entity
module v6a5074 #(
 parameter v100e1b = 22
) (
 input v0daa9e,
 output v2efea4
);
 localparam p2 = v100e1b;
 wire w0;
 wire w1;
 assign v2efea4 = w0;
 assign w1 = v0daa9e;
 v6a5074_vac7386 #(
  .N(p2)
 ) vac7386 (
  .clk_out(w0),
  .clk_in(w1)
 );
endmodule

//---------------------------------------------------
//-- PrescalerN
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Parametric N-bits prescaler
//---------------------------------------------------

module v6a5074_vac7386 #(
 parameter N = 0
) (
 input clk_in,
 output clk_out
);
 //-- Number of bits of the prescaler
 //parameter N = 22;
 
 //-- divisor register
 reg [N-1:0] divcounter;
 
 //-- N bit counter
 always @(posedge clk_in)
   divcounter <= divcounter + 1;
 
 //-- Use the most significant bit as output
 assign clk_out = divcounter[N-1];
endmodule
