// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input vd1cefe,
 input v344eeb,
 input vc5c5cb,
 input v31dfe6,
 input vcaf019,
 output v179a5c,
 output v21b970,
 output v1c6536,
 output ve78cc2,
 output vccbb9b,
 output vfc0128,
 output [0:3] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 assign v179a5c = w0;
 assign v21b970 = w5;
 assign v1c6536 = w10;
 assign w19 = v344eeb;
 assign ve78cc2 = w19;
 assign vccbb9b = w20;
 assign w21 = vd1cefe;
 assign w22 = vcaf019;
 assign w23 = v31dfe6;
 assign w24 = vc5c5cb;
 assign w25 = vd1cefe;
 assign vfc0128 = w25;
 assign w26 = v344eeb;
 assign w27 = v344eeb;
 assign w28 = v344eeb;
 assign w29 = v344eeb;
 assign w30 = v344eeb;
 assign w31 = v344eeb;
 assign w32 = v344eeb;
 assign w33 = v344eeb;
 assign w4 = w1;
 assign w9 = w6;
 assign w14 = w11;
 assign w18 = w15;
 assign w25 = w21;
 assign w26 = w19;
 assign w27 = w19;
 assign w27 = w26;
 assign w28 = w19;
 assign w28 = w26;
 assign w28 = w27;
 assign w29 = w19;
 assign w29 = w26;
 assign w29 = w27;
 assign w29 = w28;
 assign w30 = w19;
 assign w30 = w26;
 assign w30 = w27;
 assign w30 = w28;
 assign w30 = w29;
 assign w31 = w19;
 assign w31 = w26;
 assign w31 = w27;
 assign w31 = w28;
 assign w31 = w29;
 assign w31 = w30;
 assign w32 = w19;
 assign w32 = w26;
 assign w32 = w27;
 assign w32 = w28;
 assign w32 = w29;
 assign w32 = w30;
 assign w32 = w31;
 assign w33 = w19;
 assign w33 = w26;
 assign w33 = w27;
 assign w33 = w28;
 assign w33 = w29;
 assign w33 = w30;
 assign w33 = w31;
 assign w33 = w32;
 v58ed2b vb3d304 (
  .ve8318d(w1),
  .vf54559(w21),
  .va4102a(w32)
 );
 vba518e v7435fc (
  .vcbab45(w0),
  .v3ca442(w1),
  .v0e28cb(w2)
 );
 v3676a0 vd6b7e4 (
  .vcbab45(w2),
  .v0e28cb(w3)
 );
 v58ed2b vb8f8a5 (
  .ve8318d(w3),
  .vf54559(w4),
  .va4102a(w33)
 );
 v58ed2b v4b7051 (
  .ve8318d(w6),
  .vf54559(w24),
  .va4102a(w26)
 );
 vba518e vf7df84 (
  .vcbab45(w5),
  .v3ca442(w6),
  .v0e28cb(w7)
 );
 v3676a0 v0ad11f (
  .vcbab45(w7),
  .v0e28cb(w8)
 );
 v58ed2b vc6df65 (
  .ve8318d(w8),
  .vf54559(w9),
  .va4102a(w27)
 );
 v58ed2b v4a0c3f (
  .ve8318d(w11),
  .vf54559(w23),
  .va4102a(w28)
 );
 vba518e ve3d037 (
  .vcbab45(w10),
  .v3ca442(w11),
  .v0e28cb(w12)
 );
 v3676a0 v62dc33 (
  .vcbab45(w12),
  .v0e28cb(w13)
 );
 v58ed2b vcd2777 (
  .ve8318d(w13),
  .vf54559(w14),
  .va4102a(w29)
 );
 v58ed2b vd8294c (
  .ve8318d(w15),
  .vf54559(w22),
  .va4102a(w30)
 );
 vba518e vc2e6db (
  .v3ca442(w15),
  .v0e28cb(w16),
  .vcbab45(w20)
 );
 v3676a0 v247866 (
  .vcbab45(w16),
  .v0e28cb(w17)
 );
 v58ed2b v8771e5 (
  .ve8318d(w17),
  .vf54559(w18),
  .va4102a(w31)
 );
 assign vinit = 4'b0000;
endmodule

//---- Top entity
module v58ed2b #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output va58c5b,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v58ed2b_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- sys-DFF-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- System - D Flip-flop. Capture data every system clock cycle. Verilog implementation
//---------------------------------------------------

module v58ed2b_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg qi = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   qi <= d;
   
 //-- Connect the register with the
 //-- output
 assign q = qi;
endmodule
//---- Top entity
module vba518e (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vba518e_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- AND2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Two bits input And gate
//---------------------------------------------------

module vba518e_vf4938a (
 input a,
 input b,
 output c
);
 //-- AND gate
 //-- Verilog implementation
 
 assign c = a & b;
 
endmodule
//---- Top entity
module v3676a0 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v3676a0_vd54ca1 vd54ca1 (
  .a(w0),
  .q(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- NOT gate (Verilog implementation)
//---------------------------------------------------

module v3676a0_vd54ca1 (
 input a,
 output q
);
 //-- NOT Gate
 assign q = ~a;
 
 
endmodule
